---
version: "2.0"
services:
  colyseus:
    image: fenildocker/colyseus-server-unity-akash:0.0.3
    expose:
      - port: 2567
        as: 2567
        to:
          - global: true
    env:
      - NODE_ENV=production
      - PORT=2567
      - WS_PORT=2567
      - JWT_SECRET=${JWT_SECRET}
      - COLYSEUS_MONITOR_PASSWORD=${COLYSEUS_MONITOR_PASSWORD}
      - LOG_LEVEL=info
profiles:
  compute:
    colyseus:
      resources:
        cpu:
          units: 1.0
        memory:
          size: 1024Mi
        storage:
          - size: 2Gi
  placement:
    dcloud:
      pricing:
        colyseus:
          denom: ibc/170C677610AC31DF0904FFE09CD3B5C657492170E7E52372E48756B71E56F2F1
          amount: 100000
      attributes:
        host: akash
deployment:
  colyseus:
    dcloud:
      profile: colyseus
      count: 1
